### ISSUE TITLE
clang has not supported kernel build 

### ISSUE THREAD

**Issue by unicornx** [riscv-android-src/riscv-android#16]
As mentioned in https://github.com/riscv-android-src/riscv-android/blob/main/doc/prebuilt_projects.md#linux-kernel

> Currently, we have not supported building with clang

Low priority as of now.

**Comment by orick021911** [comment]
Close issue

**Comment by unicornx** [comment]
> Close issue

?

**Comment by unicornx** [comment]
closed due to I'm not working on this now.
