### ISSUE TITLE
Run Android 12 on Emulator got Segmentation fault

### ISSUE THREAD

**Issue by rayeh5** [riscv-android-src/riscv-android#21]
uname -a
Linux 5.4.0-135-generic #152~18.04.2-Ubuntu SMP Tue Nov 29 08:23:49 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Target: lunch sdk_phone64_riscv64
Question: Why Android 10 use aosp_riscv64-eng as target, but R12 use sdk_phone64_riscv64?

When run the command: 
   emulator -verbose -no-boot-anim -show-kernel -noaudio -selinux permissive -qemu -smp 2 -m 2000M -bios kernel/prebuilts/5.10/riscv64/fw_jump.bin

got messages:
[   36.073789] healthd: battery l=100 v=5000 t=25.0 h=2 st=4 c=900000 fc=300000 cc=10 chg=
[   36.251429] init: starting service 'vendor.identity-default'...
Segmentation fault (core dumped)

Do anyone run the Emulator successfully?
Thanks for your time.

The boot log is as attachment.
[rv_a12_boot.txt](https://github.com/riscv-android-src/riscv-android/files/10340954/rv_a12_boot.txt)

**Comment by funkii7** [comment]
Hey, I just wanted to add that I have the same problem using Ubuntu 20.04.
I attached a crash log
[crash0.txt](https://github.com/riscv-android-src/riscv-android/files/10530269/crash0.txt)

**Comment by rayeh5** [comment]
I found that if the user is in the "kvm" of /etc/group:
for example: kvm:x:108:rayeh5
then the emulator will crash as I reported.
But if the user is not in the "kvm", the emulator can boot into console mode, and the UI has nothing to display, is it normal for current status?
--------------
console:/ $ ls
ls
acct        data_mirror      metadata     sdcard
apex        debug_ramdisk    mnt          second_stage_resources
bin         dev              odm          storage
bugreports  etc              odm_dlkm     sys
cache       init             oem          system
config      init.environ.rc  postinstall  system_ext
d           linkerconfig     proc         vendor
data        lost+found       product      vendor_dlkm
console:/ $
----------------------------

**Comment by rayeh5** [comment]
The Phone screen does show after around 23 minutes.
So this version can boot into phone screen.
