### ISSUE TITLE
"git lfs pull" fail with android 12.

### ISSUE THREAD

**Issue by penebrain** [riscv-android-src/riscv-android#24]
Hi, I'm trying to set up Android 12 on RISC-V using the instructions from the following link: https://github.com/riscv-android-src/riscv-android/blob/main/doc/android12.md. However, when I sync the repo and use the command "git lfs pull," I encounter the error message "Failed to fetch some objects from https://github.com/riscv-android-src/platform-prebuilts-rust.git/info/lfs". Do you have any ideas on how to resolve this issue?

**Comment by MaoHan001** [comment]
The traffic of this repository has exceeded LFS bandwidth limit. You can try copying the repository to your own space and try again.

**Comment by MaoHan001** [comment]
Currently, the Android support for RISC-V has been merged upstream, and this repository is only used for archiving. If you need to obtain the new version AOSP on RISC-V support, please visit https://github.com/google/android-riscv64.

**Comment by penebrain** [comment]
@MaoHan001 Thank you a lot!
